sudo: required
language: generic
services: 
    - docker

berfore_install:
    - docker build -t ticosvd/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ticosvd/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-604676506632"
    bucket_path: "docker"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"


    