sudo: required
language: generic
services: 
    - docker

berfore_install:
    - docker build -t ticosvd/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ticosvd/docker-react npm run test -- --coverage